inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  Exclude:
    - node_modules/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - config.ru

Bundler/OrderedGems:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ExpandPathArguments:
  Exclude:
    - 'spec/rails_helper.rb'

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/ClassAndModuleChildren:
  Enabled: false