inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - node_modules/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - config.ru

Bundler/OrderedGems:
  Enabled: false
